### ISSUE TITLE
XmlNullableConverter misses DataType attribute

### ISSUE THREAD

**Issue by Backs** [netbike/netbike.xml#13]
```
public class FooNullableDateTime
{
    [System.Xml.Serialization.XmlElementAttribute("DateValue", DataType = "date")]
    public Nullable<DateTime> DateValue { get; set; }
}

[Test]
public void SerializeNullableDateTime()
{
    var value = new FooNullableDateTime
    {
        DateValue = new DateTime(2011, 11, 10),
    };
    
    var serializer = GetSerializer();
    var actual = serializer.ToXml(value);
    var expected =
        @"<fooNullableDateTime xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance""><DateValue>2011-11-10</DateValue></fooNullableDateTime>";

    Assert.That(actual, IsXml.Equals(expected).WithIgnoreDeclaration());
}
```
Result:
```
XML documents are Different.
  TextValue:
    Expected: 2011-11-10 at "/fooNullableDateTime/DateValue/text()" (1:87)
    Actual: 2011-11-10T00:00:00 at "/fooNullableDateTime/DateValue/text()" (1:126)
```

Serializer ignores `DataType="date"` value and serialize value as dateTime.

`XmlNullableConverter` contains this informaion in context:
![image](https://user-images.githubusercontent.com/5630320/195090614-bb1e9694-85f6-492c-b0ed-c3721b22f92f.png)

But `SerializeBody` creates a new context with an empty `XmlMember`:
![image](https://user-images.githubusercontent.com/5630320/195090887-2cfdf4e5-ec7a-44c9-87bb-3685c50c1789.png)
